FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y m4 scons python3-dev python-is-python3 build-essential

COPY . /repo
WORKDIR /repo
RUN python3 `which scons` build/X86/gem5.opt -j9
