FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y m4 scons python3-dev python-is-python3 build-essential

COPY . /repo
WORKDIR /repo
RUN python3 `which scons` build/X86/gem5.opt -j9

FROM ubuntu:22.04 as package
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python3-dev
COPY --from=builder /repo/build/X86/gem5.opt /
COPY --from=builder /repo/configs/example/se.py /repo/configs/example/se.py
